# Start and end dates 
[DATES]
DATESTART=2024011003
DATEEND  =2024011009

[PATHS]
# Basedir 
BASEDIR=/scratch/cvah/tunebr

# ODB path 
ODBPATH=${BASEDIR}/odb

# Workdir 
WORKDIR=${BASEDIR}/tmp 

# Temporarly extracted ODB files 
ROWS_PATH=${BASEDIR}/odb_rows  

# B matrix file 
STATFILE =/hpcperm/cvah/tuneBR_1.1.0/stab/stabcvt

# The filename where the CCMA is assumed archived in   
ODB_TEMPLATE=CCMA_minim_YYYYMMDDHH.tar      


# Some model setting
[MODEL]
CYCLE_INC=3
DELTAX   =1.3
NSMAX    =287
NFLEV    =87
REDNMC   =1.0

[OPTIONS]
# Number of CPUs for DCA files creation 
DCA_CPU= 16
# Progress bar when the ODB rows are fetched !
PROGBAR=True 

# Sigma B/O will be written in file 
OUTFILE=sigmabo_ratios

# Enable verbosity 
LLVERB=False 

# Enable file writing  
# The output files of the diffrent steps will be written in  $BASEDIR/out 
LWRITE=True 
